# Generated by Django 6.0.2 on 2026-02-26 12:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('ACTION', 'Action'), ('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('HORROR', 'Horror'), ('SCI_FI', 'Sci-Fi'), ('ROMANCE', 'Romance'), ('FANTASY', 'Fantasy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2026, 2, 26))]),
        ),
    ]
